spring:
  kafka:
    bootstrap-servers: localhost:9092
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - ${SPRING_PROFILES_ACTIVE}
server:
  port: 8083

build:
  version: "3.0"